#!/bin/bash
#
# Animal Crossing time scheduled music player. Outputs raw WAVE. By Lutarisco.
#
# Dependencies: bc, vgmstream-cli, sox (to play).
# Recommended usage:
# acplay | play --ignore-length -

# Change this to where your files lay.
dir='/home/pi/Music/ACCF'

# Adjust the format of the expected filenames as you wish. Default is '00.brstm' to '23.brstm'.
format='+%H.brstm'

# Number of seconds of fade between tracks.
fade=3

trap exit INT

while [[ "${?}" -eq 0 ]]; do
  name="$(date "${format}")"
  file="${dir}/${name}"
  data="$(vgmstream-cli -m "${file}")"
  base="$(grep start <<< "${data}" | cut -f2 -d'(' | cut -f1 -d' ')"
  if [[ "${base}" != *:* ]]; then
    base="0:${base}"
  fi
  base="$(bc -l <<< "${base%:*}*60+${base#*:}")"
  full="$(grep total <<< "${data}" | cut -f2 -d'(' | cut -f1 -d' ')"
  if [[ "${full}" != *:* ]]; then
    full="0:${full}"
  fi
  full="$(bc -l <<< "${full%:*}*60+${full#*:}")"
  left="$((3600-$(date "+%s")%3600-${fade}))"
  plays="$(bc -l <<< "(${left}-${base})/(${full}-${base})")"
  vgmstream-cli -p -f "${fade}" -l "${plays}" "${file}"
done

# If using 'sox', please use the '--ignore-length' flag with it.
# If unset, sox will stop playing when the first track finishes.
