#!/bin/bash
#
# Animal Crossing time scheduled music player. Outputs raw WAVE. By Lutarisco.
# Input either PG, CF, NL, or NH as a first argument,
# and either SUNNY, RAINY or SNOWY as a second optional argument.

# Dependencies: bc, vgmstream-cli, sox (to play).

# Recommended usage:
# acplay cf sunny | play --ignore-length -

shopt -s nocasematch

trap exit INT

# Where your files lay.
dir="/Users/benjamin/Music/Animal Crossing"
towntune="${dir}/WildWorldDefaultTune.wav"

# Fade-out before next hour, in seconds.
fade=3

case "${2}" in
RAINY)
  weather=RAINY
  ;;
SNOWY)
  weather=SNOWY
  ;;
*)
  weather=SUNNY
  ;;
esac

case "${1}" in
PG)
  dir="${dir}/ACPG"
  date="+%H_${weather}.bcstm"
  ;;
CF)
  dir="${dir}/ACCF"
  date="+%H_${weather}.brstm"
  ;;
NL)
  dir="${dir}/ACNL"
  date="+%H_${weather}.bcstm"
  ;;
NH)
  dir="${dir}/ACNH"
  date="+%H_${weather}.bwav"
  ;;
*)
  >&2 echo 'Available options: PG, CF, NL, NH'
  exit 1
  ;;
esac

while [[ "${?}" -eq 0 ]]; do
  file="${dir}/$(date "${date}")"
  data="$(vgmstream-cli -m "${file}")"
  base="$(grep '^loop start' <<< "${data}" | cut -d' ' -f 3)"
  full="$(grep '^loop end' <<< "${data}" | cut -d' ' -f 3)"
  rate="$(grep '^sample rate' <<< "${data}" | cut -d' ' -f 3)"
  left="$(((3600-$(date "+%s")%3600-${fade})*${rate}))"
  plays="$(bc -l <<< "(${left}-${base})/(${full}-${base})")"
  vgmstream-cli -p -f "${fade}" -l "${plays}" "${file}"
  vgmstream-cli -p "${towntune}"
done

# If using 'sox', please use the '--ignore-length' flag with it.
# If unset, sox will stop playing when the first track finishes.
